---
# tasks file for nginx-lb

- block:
  - include_tasks: install-repo.yml
  - include_tasks: config-selinux.yml

  - name: ensure nginx package is present
    yum:
      name:
        - nginx
      state: present

  - name: ensure nginx config directory is present
    file:
      path: /etc/nginx/conf.d
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: ensure nginx configuration is set
    template:
      src: conf.j2
      dest: /etc/nginx/nginx.conf
    notify:
      - restart nginx

  - name: ensure vhost file(s) are populated in conf directory
    template:
      src: "{{ item.template | default('vhosts.j2') }}"
      dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
    with_items:
      - "{{ vhosts }}"

  - name: generate ssl certificates
    include_tasks: generate-ssl_certs.yml

  - name: check if web and ssl ports are available
    wait_for:
      port: "{{ item }}"
      state: stopped
      delay: 5
      timeout: 10
      msg: "existing server on port {{ item }}." 
    with_items:
      - "{{ lb.web_port }}"
      - "{{ lb.ssl_port }}"

  - name: ensure nginx is started and enabled
    systemd:
      name: nginx
      state: started
      enabled: true

  - import_tasks: config-firewall.yml
  become: true

