---
# vars file for nginx-wap
vhosts:
  - name: siem
    srv_ip0: 192.168.4.43
    srv_ip1: 192.168.4.44
    srv_ip2: 192.168.4.45
    srv_port: 8000
    srv_fqdn: siem.fakelabs.io
    ssl_port: 443
    listen_port: 80
    tls_certificate_path: /etc/nginx/ssl/wap-cert.crt
    tls_certprivkey_path: /etc/nginx/ssl/wap-priv.key
