---
- name: ensure semanage dependencies are installed
  yum:
    name:
      - policycoreutils-python
    state: present

- name: ensure selinux exceptions for nginx upstream ports are active
  seport:
    ports: "{{ item.srv_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  with_items:
    - "{{ vhosts }}"

