---
- name: ensure openssl dependencies are present
  yum:
    name: 
      - openssl
      - python-pip
      - python-setuptools
    state: latest

- name: pyOpenSSL deprecated installing 'cryptography' via pip
  pip:
    name: cryptography

- name: create ssl directory
  file:
    path: "{{ wap.tls_dir }}"
    state: directory
    mode: 0755

- name: generate private key
  openssl_privatekey:
    path: "{{ wap.tls_dir }}/{{ wap.tls_privkey }}"

- name: generate CSR
  openssl_csr:
    path: "{{ wap.tls_dir }}/{{ wap.tls_csr }}"
    privatekey_path: "{{ wap.tls_dir }}/{{ wap.tls_privkey }}"
    common_name: devops.fakelabs.io
    country_name: US
    organization_name: fakelabs

- name: generate self-signed certificate
  openssl_certificate:
    path: "{{ wap.tls_dir }}/{{ wap.tls_certificate }}"
    csr_path: "{{ wap.tls_dir }}/{{ wap.tls_csr }}"
    privatekey_path: "{{ wap.tls_dir }}/{{ wap.tls_privkey }}"
    provider: selfsigned
